### ISSUE TITLE
Not Working on version 2.x.x

### ISSUE THREAD

**Issue by NandaCPT** [Verdoso/multi-mybatis-demo#2]
How can i implement this for Spring Boot version 2.x.x?

**Comment by Verdoso** [comment]
The classes in https://github.com/Verdoso/multi-mybatis-demo/tree/master/src/main/java/org/greeneyed/multimybatisdemo/config can be used with Spring Boot 2.X pretty much unchanged. We use them like that, no problem.
The only thing that changes to go to version 2 is the pom and the application properties, but the datasources configuration works as-is.

**Comment by NandaCPT** [comment]
I'm trying to access two databases, oracle and mariadb, but an error occurs

**Comment by NandaCPT** [comment]
i think i miss this one
// Filled up with the properties specified about thanks to Spring Boot black
// magic
can you explain this part?

**Comment by Verdoso** [comment]
What it means is that when you tag the method that creates a Bean with @ConfigurationProperties(prefix = "datasources.one"), what it does is grab the properties under that preffix and apply them to the Bean that the method returns.
You return and empty object (just newly created) and Spring "magically" sets all the properties that are in the the configuration file (https://github.com/Verdoso/multi-mybatis-demo/blob/master/src/main/resources/application.yml) before actually returning the object.
So, Spring sees a property datasources.one.jdbcUrl and does a dataSource.setJdbcurl(propertyValue) on the object that you return.

**Comment by NandaCPT** [comment]
oke thank you, its worked now, my problem is in application properties, need need to be changed to jdbc-url (not just url or jdbcUrl ) if you want to add multi datasource.
Thank you for your response

**Comment by Verdoso** [comment]
Glad that it worked. Sometimes the black magic of this kind of frameworks makes it hard to understand what's going on.
